credentials:
  usernames:
    admin:
      email: admin@magnolia.local
      name: Admin
      password: '$2b$12$KIXl3hsQbEXEiCjbTPXyUOaGqOYSEiEkVtk0pFWe7hnnY0xeK9DyW'
cookie:
  name: magnolia_auth
  key: some_random_key
  expiry_days: 7
preauthorized:
  emails:
    - admin@magnolia.local